const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const app = fs.readFileSync(path.join(root, 'public', 'app.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'public', 'styles.css'), 'utf8');
const html = fs.readFileSync(path.join(root, 'public', 'index.html'), 'utf8');
const serviceWorker = fs.readFileSync(path.join(root, 'public', 'sw.js'), 'utf8');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');

test('finance, reports and maintenance expose the expected view tabs', () => {
  assert.match(app, /financeViewTab/);
  assert.match(app, /Contas a pagar e receber/);
  assert.match(app, /finance-pending-dashboard/);
  assert.match(app, /financeMonthCommandPanel/);
  assert.match(app, /finance-month-command/);
  assert.match(app, /data-finance-month-action/);
  assert.match(app, /reconciliationHistory/);
  assert.match(app, /Parcelar valor total/);
  assert.match(app, /data-reverse-payment/);
  assert.match(app, /financialAccountNotifications/);
  assert.match(app, /Orçamento mensal por categoria/);
  assert.match(app, /Operação e financeiro/);
  assert.match(app, /Saldo das contas/);
  assert.match(app, /dashboardAccountBreakdown/);
  assert.match(app, /accountBalanceBreakdownUntilDate/);
  assert.match(app, /latestCashEntryForAccount/);
  assert.match(app, /data-cash-account-summary="pf"/);
  assert.match(app, /data-cash-account-summary="pj"/);
  assert.doesNotMatch(app, /id="zero-account-balance/);
  assert.match(app, /id="maintenance-zero-account"/);
  assert.match(app, /zeroAccountBalanceAtDate/);
  assert.match(app, /projectedBalances30/);
  assert.match(app, /cash-forecast-metric/);
  assert.match(app, /cashEntryDraft/);
  assert.match(app, /normalizedCashEntryDraft/);
  assert.match(app, /lockFormSubmission/);
  assert.match(app, /dataset\.submitting/);
  assert.match(app, /return \[\.\.\.entries\]\.reverse\(\)/);
  assert.match(app, /cashAccountOptionsHtml/);
  assert.match(app, /reconciliationCashAccount/);
  assert.match(app, /cash-account-summary/);
  assert.match(app, /Unificado PF \+ PJ/);
  assert.doesNotMatch(app, /Entrada PF|Entrada PJ/);
  assert.match(app, /daily-reconciliation-account/);
  assert.match(app, /data-export-report="accountant-package"/);
  assert.match(app, /downloadAccountantPackage/);
  assert.match(app, /accountPackageSummaryRows/);
  assert.match(app, /accountPackagePfRows/);
  assert.match(app, /accountPackagePjRows/);
  assert.match(app, /financial-account-cash-account/);
  assert.match(app, /localStorage\.setItem\("cashEntryDraft"/);
  assert.doesNotMatch(app, /Saldo insuficiente na conta para esta sa/);
  assert.doesNotMatch(app, /Cofrinho cobriu/);
  assert.match(app, /savingsHistoryDetailHtml/);
  assert.match(app, /dailyClosingChecklistHtml/);
  assert.match(app, /data-daily-closing-action/);
  assert.match(app, /data-focus-cash-entry/);
  assert.match(app, /data-cash-entry-date="today"/);
  assert.match(app, /data-cash-entry-date="yesterday"/);
  assert.match(app, /data-cash-quick="pending"/);
  assert.match(app, /data-cash-quick="savings"/);
  assert.match(app, /data-cash-quick="withdrawals"/);
  assert.match(app, /storeSalesFilterDefaults/);
  assert.match(app, /storeSalesMonthComparison/);
  assert.match(app, /id="store-sales-filter-form"/);
  assert.match(app, /id="store-sales-filter-type"/);
  assert.match(app, /Combos no período/);
  assert.match(app, /Unidades nos combos/);
  assert.match(app, /data-store-sales-comparison/);
  assert.match(app, /name="saleType"/);
  assert.match(app, /name="unitsPerCombo"/);
  assert.match(app, /data-store-sale-total/);
  assert.match(app, /name="labels"/);
  assert.match(app, /name="telephony"/);
  assert.match(app, /value="kg"/);
  assert.match(app, /value="box"/);
  assert.match(app, /function storeSaleUnitQuantity/);
  assert.match(app, /data\.storeSales\.map\(storeSaleReportRow\)/);
  assert.match(css, /\.store-sale-type-options/);
  assert.match(css, /\.store-sale-total/);
  assert.match(css, /\.table-wrap table \{\s*width: 100%;\s*min-width: 0;/);
  assert.match(
    server,
    /\[\s*'Data',\s*'Produto',\s*'Tipo',\s*'Quantidade',\s*'Unidades por combo',\s*'Total de unidades'/
  );
  const cashTabs = app.match(/const cashPanelTabs = \[([\s\S]*?)\];/);
  const storeTabs = app.match(/const storeTabs = \[([\s\S]*?)\];/);
  assert.ok(cashTabs);
  assert.ok(storeTabs);
  assert.doesNotMatch(cashTabs[1], /\["channels", "Canais"\]/);
  assert.match(storeTabs[1], /\["channels", "Canais"\]/);
  assert.match(storeTabs[1], /\["products", "Produtos"\]/);
  assert.match(app, /\/loja\?view=channels/);
  assert.match(app, /bindChannelReceipts\(renderStoreSales/);
  assert.match(app, /id="store-product-form"/);
  assert.match(app, /name="pricingRecipeId"/);
  assert.match(app, /name="productId"/);
  assert.match(app, /id="store-product-quantities-form"/);
  assert.match(app, /data-store-product-quantity/);
  assert.match(app, /function storeProductMonthlyHistory/);
  assert.match(app, /storeProductQuantities: state\.storeProductQuantities/);
  assert.match(app, /storeProductQuantities: state\.storeProductQuantities\.filter/);
  assert.match(server, /'storeProducts'/);
  assert.match(server, /'storeProductQuantities'/);
  assert.match(css, /\.store-product-quantity-row/);
  assert.match(app, /\["dashboard", "Visão geral"\]/);
  assert.match(app, /\["ingredients", "Ingredientes"\]/);
  assert.match(app, /\["recipes", "Receitas"\]/);
  assert.match(app, /\["costs", "Custos rateados"\]/);
  assert.match(app, /id="pricing-ingredient-form"/);
  assert.match(app, /id="pricing-recipe-form"/);
  assert.match(app, /id="pricing-shared-cost-form"/);
  assert.match(app, /function pricingRecipeMetrics/);
  assert.match(app, /function storeProductPerformanceRows/);
  assert.match(app, /function storeProductPerformancePanel/);
  assert.match(app, /data-store-product-performance/);
  assert.match(app, /\["products", "Produtos"\]/);
  assert.match(app, /function pricingSharedCosts/);
  assert.match(app, /function pricingDecimalNumber/);
  assert.match(app, /function pricingUnitCostMoney/);
  assert.match(app, /function storeAverageMonthlyUnits/);
  assert.match(app, /pricingRecipes: state\.pricingRecipes/);
  assert.match(app, /Custos extraordinários/);
  assert.match(app, /Lucro estimado por lote/);
  assert.match(app, /Cumbuca mais lucrativa/);
  assert.match(server, /'pricingRecipes'/);
  assert.match(server, /function calculatePricing/);
  assert.match(css, /\.pricing-dashboard-grid/);
  assert.match(css, /\.pricing-recipe-layout/);
  assert.match(css, /\.pricing-status\.profitable/);
  assert.match(app, /name="expectedVanessa"/);
  assert.match(app, /name="expectedRaquel"/);
  assert.match(app, /Quanto realmente foi retirado/);
  assert.match(app, /Saldo pendente acumulado/);
  assert.match(app, /partnerPendingLabel/);
  assert.doesNotMatch(app, /Antecipado|Acima do calculado/);
  assert.match(css, /\.budget-progress/);
  assert.match(css, /\.cash-date-shortcuts/);
  assert.match(css, /\.cash-account-summary/);
  assert.match(css, /\.cash-account-metric/);
  assert.match(css, /\.dashboard-account-breakdown/);
  assert.match(css, /\.account-balance-metric/);
  assert.match(css, /\.cash-forecast-metric/);
  assert.match(css, /\.store-sales-filter/);
  assert.match(css, /\.store-sales-comparison/);
  assert.match(css, /\.daily-closing-guide/);
  assert.match(css, /\.closing-check/);
  assert.match(css, /\.linked-action-row/);
  assert.match(css, /\.withdrawal-value-group/);
  assert.match(app, /reportViewTab/);
  assert.match(app, /data-maintenance-pane="integrity"/);
  assert.match(app, /updateMaintenanceTabRoute/);
  assert.match(app, /maintenanceTabForTarget/);
  assert.match(app, /scrollMaintenanceTarget/);
  assert.match(app, /permission-fieldset/);
  assert.match(app, /integration-status/);
  assert.match(app, /function normalizedCleanupYear/);
  assert.match(app, /numberYear < 2000/);
  assert.match(app, /cleanupYearField && cleanupPreviewBox/);
  assert.match(css, /\.account-row/);
  assert.match(css, /\.pending-grid/);
  assert.match(css, /\.finance-month-summary/);
  assert.match(css, /\.month-status-pill/);
  assert.match(css, /\.maintenance-grid \.period-picker button/);
});

test('mobile tables receive column labels', () => {
  assert.match(app, /function enhanceResponsiveTables/);
  assert.match(css, /content:\s*attr\(data-label\)/);
});

test('HTML and service worker use the same asset versions', () => {
  const cssVersion = html.match(/styles\.css\?v=([^"]+)/)?.[1];
  const appVersion = html.match(/app\.js\?v=([^"]+)/)?.[1];

  assert.ok(cssVersion);
  assert.ok(appVersion);
  assert.match(serviceWorker, new RegExp(`styles\\.css\\?v=${cssVersion}`));
  assert.match(serviceWorker, new RegExp(`app\\.js\\?v=${appVersion}`));
});
