const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const app = fs.readFileSync(path.join(root, 'public', 'app.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'public', 'styles.css'), 'utf8');
const html = fs.readFileSync(path.join(root, 'public', 'index.html'), 'utf8');
const serviceWorker = fs.readFileSync(path.join(root, 'public', 'sw.js'), 'utf8');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');

test('narrow browser windows keep horizontal page scrolling available', () => {
  assert.match(css, /html \{\s*overflow-x: auto;/);
  assert.match(css, /body \{[\s\S]*?overflow-x: visible;/);
  assert.doesNotMatch(css, /html \{\s*overflow-x: hidden;/);
  assert.match(css, /@media \(min-width: 561px\) and \(max-width: 1100px\)/);
  assert.match(css, /grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/);
  assert.match(app, /cash-filter-disclosure/);
  assert.match(app, /advancedCashFilterActive/);
  assert.match(css, /cash-ledger-panel > \.summary/);
  assert.match(html, /id="hero-motto"/);
  assert.match(html, /class="hero quote-mode"/);
  assert.match(
    html,
    /<h1 id="page-title">“É claro que a vida é boa[\s\S]*?Mas acontece que eu sou triste[\s\S]*?<\/h1>/
  );
  assert.doesNotMatch(app, /title\.textContent = "Visão Geral"/);
  assert.match(app, /dailyHeroMottos/);
  assert.match(app, /dailyHeroMessages/);
  assert.match(app, /showHomeHero/);
  assert.match(app, /quote-compact/);
  assert.match(app, /Boolean\(message\.compact\)/);
  assert.match(app, /message\.text\.length > 180 \|\| message\.text\.includes/);
  assert.match(app, /showStandardHero/);
  assert.match(app, /dailyCashMottos/);
  assert.match(app, /cashMottoForDate/);
  assert.match(app, /pageTitle === "Fluxo de Caixa"/);
  assert.match(app, /HOME_HERO_LAST_INDEX_KEY/);
  assert.match(app, /Math\.random\(\)/);
  assert.match(app, /window\.sessionStorage\.setItem/);
  assert.match(app, /Carlos Drummond de Andrade/);
  assert.match(app, /Vinicius de Moraes/);
  assert.match(app, /Chico Buarque/);
  assert.match(app, /Jorge Vercillo/);
  assert.match(app, /Los Hermanos/);
  assert.match(app, /Luis Fernando Verissimo/);
  assert.match(app, /Clarice Lispector/);
  assert.doesNotMatch(app, /ANAVITÓRIA/);
  const heroMessages = app.match(
    /const dailyHeroMessages = \[([\s\S]*?)\n\];\n\nconst HOME_HERO_LAST_INDEX_KEY/
  );
  assert.ok(heroMessages);
  assert.equal((heroMessages[1].match(/credit:/g) || []).length, 80);
  assert.equal((heroMessages[1].match(/credit: "Carlos Drummond de Andrade/g) || []).length, 16);
  assert.equal((heroMessages[1].match(/credit: "Vinicius de Moraes/g) || []).length, 16);
  assert.equal((heroMessages[1].match(/credit: "Chico Buarque/g) || []).length, 16);
  assert.equal((heroMessages[1].match(/credit: "Jorge Vercillo/g) || []).length, 10);
  assert.equal((heroMessages[1].match(/credit: "Los Hermanos/g) || []).length, 10);
  assert.equal((heroMessages[1].match(/credit: "Luis Fernando Verissimo/g) || []).length, 6);
  assert.equal((heroMessages[1].match(/credit: "Clarice Lispector/g) || []).length, 6);
  assert.match(
    heroMessages[1],
    /text: "E agora, José\?[\s\S]*?a noite esfriou\."[\s\S]*?Carlos Drummond de Andrade · José/
  );
  assert.match(
    heroMessages[1],
    /João amava Teresa[\s\S]*?J\. Pinto Fernandes\\nque não tinha entrado na história\./
  );
  assert.match(
    heroMessages[1],
    /text: "É claro que a vida é boa[\s\S]*?Mas acontece que eu sou triste\.\.\."[\s\S]*?Vinicius de Moraes · Dialética/
  );
  assert.match(heroMessages[1], /Vinicius de Moraes · Dialética",[\s\S]*?compact: true/);
  const cashMottos = app.match(
    /const dailyCashMottos = \[([\s\S]*?)\n\];\n\nconst dailyHeroMessages/
  );
  assert.ok(cashMottos);
  assert.equal((cashMottos[1].match(/"Pitada do dia:/g) || []).length, 30);
  assert.match(css, /\.hero-motto/);
  assert.match(css, /\.hero\.quote-mode h1/);
  assert.match(html, /class="hero-logo hero-map"/);
  assert.match(html, /class="hero-brand-art"/);
  assert.match(html, /class="hero-bowl-logo"/);
  assert.match(html, /class="brand-copy"/);
  assert.match(html, /class="brand-mark"[\s\S]*?<img src="\/logo-cumbuca-original\.png"/);
  assert.equal(fs.existsSync(path.join(root, 'public', 'logo-cumbuca-original.png')), true);
  assert.match(html, /src="\/mapa-cumbuca\.png"/);
  assert.match(serviceWorker, /\/mapa-cumbuca\.png/);
  assert.equal(fs.existsSync(path.join(root, 'public', 'mapa-cumbuca.png')), true);
});

test('finance, reports and maintenance expose the expected view tabs', () => {
  assert.match(app, /financeViewTab/);
  assert.match(app, /Contas a pagar e receber/);
  assert.match(app, /Funcionários da Cumbuca/);
  assert.match(app, /financialEmployeesPanel/);
  assert.match(app, /financialEmployeeForEntry/);
  assert.match(app, /financial-employee-form/);
  assert.match(app, /cash-employee-field/);
  assert.match(app, /today-expense-employee-field/);
  assert.match(app, /financial-account-employee/);
  assert.match(app, /employeeId/);
  assert.match(server, /employees: \[\]/);
  assert.match(app, /finance-pending-dashboard/);
  assert.match(app, /financeMonthCommandPanel/);
  assert.match(app, /financialPlanVsActualPanel/);
  assert.match(app, /plan-vs-actual-panel/);
  assert.match(app, /finance-month-command/);
  assert.match(app, /data-finance-month-action/);
  assert.match(app, /reconciliationHistory/);
  assert.match(app, /Parcelar valor total/);
  assert.match(app, /data-reverse-payment/);
  assert.match(app, /financialAccountNotifications/);
  assert.match(app, /Orçamento mensal por categoria/);
  assert.match(app, /Operação e financeiro/);
  assert.match(app, /Saldo das contas/);
  assert.match(app, /dashboardAccountBreakdown/);
  assert.match(app, /accountBalanceBreakdownUntilDate/);
  assert.match(app, /latestCashEntryForAccount/);
  assert.match(app, /data-cash-account-summary="pf"/);
  assert.match(app, /data-cash-account-summary="pj"/);
  assert.match(app, /data-cash-account-summary="unassigned"/);
  assert.match(app, /Resultado do filtro/);
  assert.match(app, /Entradas - saídas exibidas/);
  assert.doesNotMatch(app, /id="zero-account-balance/);
  assert.match(app, /id="maintenance-zero-account"/);
  assert.match(app, /zeroAccountBalanceAtDate/);
  assert.match(app, /projectedBalances30/);
  assert.match(app, /cash-forecast-metric/);
  assert.match(app, /cashEntryDraft/);
  assert.match(app, /normalizedCashEntryDraft/);
  assert.match(app, /lockFormSubmission/);
  assert.match(app, /dataset\.submitting/);
  assert.match(app, /cashSort: \{ key: "date", direction: "desc" \}/);
  assert.match(app, /return comparison \|\| \(a\.index - b\.index\) \* direction/);
  assert.match(app, /cashAccountOptionsHtml/);
  assert.match(app, /reconciliationCashAccount/);
  assert.match(app, /cash-account-summary/);
  assert.match(app, /Unificado PF \+ PJ/);
  assert.doesNotMatch(app, /Entrada PF|Entrada PJ/);
  assert.match(app, /daily-reconciliation-account/);
  assert.match(app, /data-export-report="accountant-package"/);
  assert.match(app, /downloadAccountantPackage/);
  assert.match(app, /accountPackageSummaryRows/);
  assert.match(app, /accountPackagePfRows/);
  assert.match(app, /accountPackagePjRows/);
  assert.match(app, /financial-account-cash-account/);
  assert.match(app, /localStorage\.setItem\("cashEntryDraft"/);
  assert.doesNotMatch(app, /Saldo insuficiente na conta para esta sa/);
  assert.doesNotMatch(app, /Cofrinho cobriu/);
  assert.match(app, /savingsHistoryDetailHtml/);
  assert.match(app, /dailyClosingChecklistHtml/);
  assert.match(app, /data-daily-closing-action/);
  assert.match(app, /data-focus-cash-entry/);
  assert.match(app, /data-cash-entry-date="today"/);
  assert.match(app, /data-cash-entry-date="yesterday"/);
  assert.match(app, /data-cash-quick="pending"/);
  assert.match(app, /data-cash-quick="savings"/);
  assert.match(app, /data-cash-quick="withdrawals"/);
  assert.match(app, /storeSalesFilterDefaults/);
  assert.match(app, /storeSalesMonthComparison/);
  assert.match(app, /id="store-sales-filter-form"/);
  assert.match(app, /id="store-sales-filter-type"/);
  assert.match(app, /id="store-sales-filter-product"/);
  assert.match(app, /storeSalesSummary/);
  assert.match(app, /data-store-sales-filter-combos/);
  assert.match(app, /data-store-sales-filter-standalone-units/);
  assert.match(app, /data-store-sales-filter-combo-units/);
  assert.match(app, /data-store-sales-filter-best-day/);
  assert.match(app, /data-store-sales-day-ranking/);
  assert.match(app, /Combos no período/);
  assert.match(app, /Unidades nos combos/);
  assert.match(app, /data-store-sales-comparison/);
  assert.match(app, /name="saleType"/);
  assert.match(app, /name="unitsPerCombo"/);
  assert.match(app, /data-store-sale-total/);
  assert.doesNotMatch(app, /name="labels"/);
  assert.match(app, /name="telephony"/);
  assert.match(app, /Embalagens e etiquetas não entram aqui/);
  assert.match(app, /value="kg"/);
  assert.match(app, /value="box"/);
  assert.match(app, /function storeSaleUnitQuantity/);
  assert.match(app, /data\.storeSales\.map\(storeSaleReportRow\)/);
  assert.match(css, /\.store-sale-type-options/);
  assert.match(css, /\.store-sale-total/);
  assert.match(css, /\.table-wrap table \{\s*width: 100%;\s*min-width: 0;/);
  assert.match(
    server,
    /\[\s*'Data',\s*'Produto',\s*'Tipo',\s*'Quantidade',\s*'Unidades por combo',\s*'Total de unidades'/
  );
  const cashTabs = app.match(/const cashPanelTabs = \[([\s\S]*?)\];/);
  const storeTabs = app.match(/const storeTabs = \[([\s\S]*?)\];/);
  assert.ok(cashTabs);
  assert.ok(storeTabs);
  assert.doesNotMatch(cashTabs[1], /\["channels", "Canais"\]/);
  assert.match(storeTabs[1], /\["channels", "Canais"\]/);
  assert.match(storeTabs[1], /\["products", "Produtos"\]/);
  assert.match(app, /\/loja\?view=channels/);
  assert.match(app, /bindChannelReceipts\(renderStoreSales/);
  assert.match(app, /id="store-product-form"/);
  assert.match(app, /name="pricingRecipeId"/);
  assert.match(app, /name="productId"/);
  assert.match(app, /id="store-product-quantities-form"/);
  assert.match(app, /data-store-product-quantity/);
  assert.match(app, /function storeProductMonthlyHistory/);
  assert.match(app, /storeProductQuantities: state\.storeProductQuantities/);
  assert.match(app, /storeProductQuantities: state\.storeProductQuantities\.filter/);
  assert.match(server, /'storeProducts'/);
  assert.match(server, /'storeProductQuantities'/);
  assert.match(css, /\.store-product-quantity-row/);
  assert.match(app, /\["dashboard", "Visão geral"\]/);
  assert.match(app, /\["ingredients", "Ingredientes"\]/);
  assert.match(app, /\["recipes", "Receitas"\]/);
  assert.match(app, /\["costs", "Custos rateados"\]/);
  assert.match(app, /id="pricing-ingredient-form"/);
  assert.match(app, /id="pricing-recipe-form"/);
  assert.match(app, /id="pricing-shared-cost-form"/);
  assert.match(app, /id="save-pricing-staff"/);
  assert.match(app, /data-pricing-staff-member/);
  assert.match(app, /function pricingStaffMembers/);
  assert.match(app, /function pricingStaffMembersFromForm/);
  assert.match(app, /Mão de obra cadastrada anteriormente/);
  assert.match(app, /function pricingRecipeMetrics/);
  assert.match(app, /function pricingRecipeIsComplete/);
  assert.match(app, /function pricingRecipeForMenuItem/);
  assert.match(app, /data-menu-recipe-select/);
  assert.match(app, /data-menu-recipe-summary/);
  assert.match(server, /recipeId: String\(found\.recipeId/);
  assert.match(app, /PRICING_RECIPE_BATCH_SIZE = 50/);
  assert.match(app, /function pricingRecipeIngredientBatchSize/);
  assert.match(app, /ingredientBatchSize: PRICING_RECIPE_BATCH_SIZE/);
  assert.match(app, /Informe depois o lote para 50 pratos/);
  assert.match(app, /data-pricing-save-next/);
  assert.match(app, /data-pricing-create-base/);
  assert.match(app, /Cadastrar receita e continuar/);
  assert.match(app, /data-pricing-add-ingredient-for-recipe/);
  assert.match(app, /Ingredientes pendentes/);
  assert.match(app, /function storeProductPerformanceRows/);
  assert.match(app, /function storeProductPerformancePanel/);
  assert.match(app, /function weeklyRecipeProfitabilityRows/);
  assert.match(app, /function businessProfitabilityPanel/);
  assert.match(app, /\["profitability", "Rentabilidade"\]/);
  assert.match(app, /data-profitability-panel/);
  assert.match(app, /data-store-product-performance/);
  assert.match(app, /\["products", "Produtos"\]/);
  assert.match(app, /function pricingSharedCosts/);
  assert.match(app, /function pricingDecimalNumber/);
  assert.match(app, /function pricingUnitCostMoney/);
  assert.match(app, /function storeAverageMonthlyUnits/);
  assert.match(app, /pricingRecipes: state\.pricingRecipes/);
  assert.match(app, /Custos extraordinários/);
  assert.match(app, /Lucro estimado por lote/);
  assert.match(app, /Cumbuca mais lucrativa/);
  assert.match(server, /'pricingRecipes'/);
  assert.match(server, /function calculatePricing/);
  assert.match(server, /ingredientBatchSize/);
  assert.match(server, /Ingredientes pendentes/);
  assert.match(css, /\.pricing-dashboard-grid/);
  assert.match(css, /\.pricing-staff-editor/);
  assert.match(css, /\.pricing-staff-total/);
  assert.match(css, /\.pricing-recipe-layout/);
  assert.match(css, /\.pricing-recipe-batch-note/);
  assert.match(css, /\.pricing-recipe-step/);
  assert.match(css, /\.pricing-workflow-context/);
  assert.match(css, /\.pricing-status\.pending/);
  assert.match(css, /\.pricing-status\.profitable/);
  assert.match(app, /name="expectedVanessa"/);
  assert.match(app, /name="expectedRaquel"/);
  assert.match(app, /Conta de onde saiu o dinheiro/);
  assert.match(app, /value="unassigned"/);
  assert.match(app, /Quanto realmente sairá da conta agora/);
  assert.match(app, /Valores compensados ao caixa/);
  assert.match(app, /name="priorVanessa"/);
  assert.match(app, /name="priorRaquel"/);
  assert.match(app, /Base da divisão/);
  assert.match(app, /partnerCashOffsetLabel/);
  assert.match(app, /partnerPendingLabel/);
  assert.doesNotMatch(app, /Antecipado|Acima do calculado/);
  assert.match(css, /\.budget-progress/);
  assert.match(css, /\.cash-date-shortcuts/);
  assert.match(css, /\.cash-account-summary/);
  assert.match(css, /\.cash-account-metric/);
  assert.match(css, /\.dashboard-account-breakdown/);
  assert.match(css, /\.account-balance-metric/);
  assert.match(css, /\.cash-forecast-metric/);
  assert.match(css, /\.store-sales-filter/);
  assert.match(css, /\.store-sales-summary/);
  assert.match(css, /\.store-sales-day-ranking/);
  assert.match(css, /\.store-sales-comparison/);
  assert.match(css, /\.daily-closing-guide/);
  assert.match(css, /\.closing-check/);
  assert.match(css, /\.linked-action-row/);
  assert.match(css, /\.withdrawal-value-group/);
  assert.match(app, /reportViewTab/);
  assert.match(html, />Operação<\/a>/);
  assert.match(app, /function operationAgendaItems/);
  assert.match(app, /function actionableManagementAlerts/);
  assert.match(app, /data-alert-category/);
  assert.match(app, /name="defaultPackagingCost"/);
  assert.match(app, /name="defaultDesiredMarginPercent"/);
  assert.match(app, /name="backupReminderDays"/);
  assert.match(app, /id="maintenance-backup-health"/);
  assert.match(app, /function automaticBackupHealthHtml/);
  assert.match(app, /data-maintenance-pane="integrity"/);
  assert.match(app, /updateMaintenanceTabRoute/);
  assert.match(app, /maintenanceTabForTarget/);
  assert.match(app, /scrollMaintenanceTarget/);
  assert.match(app, /permission-fieldset/);
  assert.match(app, /integration-status/);
  assert.match(app, /function normalizedCleanupYear/);
  assert.match(app, /numberYear < 2000/);
  assert.match(app, /cleanupYearField && cleanupPreviewBox/);
  assert.match(css, /\.account-row/);
  assert.match(css, /\.pending-grid/);
  assert.match(css, /\.finance-month-summary/);
  assert.match(css, /\.month-status-pill/);
  assert.match(css, /\.maintenance-grid \.period-picker button/);
  assert.match(css, /\.operation-priority-list/);
  assert.match(css, /\.menu-recipe-summary/);
  assert.match(css, /\.plan-vs-actual-grid/);
  assert.match(css, /\.maintenance-health-grid/);
});

test('mobile tables receive column labels', () => {
  assert.match(app, /function enhanceResponsiveTables/);
  assert.match(css, /content:\s*attr\(data-label\)/);
});

test('HTML and service worker use the same asset versions', () => {
  const cssVersion = html.match(/styles\.css\?v=([^"]+)/)?.[1];
  const appVersion = html.match(/app\.js\?v=([^"]+)/)?.[1];

  assert.ok(cssVersion);
  assert.ok(appVersion);
  assert.match(serviceWorker, new RegExp(`styles\\.css\\?v=${cssVersion}`));
  assert.match(serviceWorker, new RegExp(`app\\.js\\?v=${appVersion}`));
});
